# Generated by Django 5.0 on 2023-12-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='criterion1_score',
            new_name='fiction_score',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='criterion2_score',
            new_name='non_fiction_score',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='criterion1_score',
            new_name='fiction_score',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='criterion2_score',
            new_name='non_fiction_score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='criterion3_score',
        ),
    ]
